### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by abbychau** [adi518/vue-facebook-login-component#17]
I have found a similar topic here.
Refer : https://github.com/adi518/vue-facebook-login-component/pull/15

is regenerator-runtime actually needed for this componenent?
<img width="662" alt="Screen Shot 2019-10-08 at 12 00 28" src="https://user-images.githubusercontent.com/350283/66364035-42caeb00-e9c3-11e9-9c2d-8017e086a0bf.png">

**Comment by Mixelated** [comment]
same problem here

**Comment by adi518** [comment]
It's using async/await syntax and apparently some consumers have issues with it. I need to try and look at this again, but for the time being it looks like there's a solution. I'm contemplating adding `regenerator-runtime`  as a peer dependency, but unless everyone has this issue, it might be redundant. Since I can't tell how many users experience this, we'll skip it for now.

As far as syntax goes, I'd probably try this, at the top of my `main.js`:
```js
import "regenerator-runtime";
```
```
