### ISSUE TITLE
How to open facebook login dialog in the same window instead of popup window?

### ISSUE THREAD

**Issue by nicolay-zlobin** [adi518/vue-facebook-login-component#45]

**Comment by desert** [comment]
I don't think it is possible, last time I tried the API forced you to do it on new window. But maybe that has changed in the last years.

**Comment by adi518** [comment]
You need to read about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). The popup opens up a Facebook domain, so it can talk to its API. You can't make requests from domain A to domain B, unless the server is configured to allow that, which in most cases it isn't, because it's a security breach. Imagine someone could hijack your token/cookie and then use that to make a request to your bank on your behalf from a foreign domain.

**Comment by nicolay-zlobin** [comment]
The task was to make a login as in [mydates.me](http://mydates.me) (click START > Redirect to facebook > Type Login/Pass > Redirect back).

Found out that we can make it by manually building a login flow though:

```
https://www.facebook.com/v7.0/dialog/oauth?
  client_id={app-id}
  &redirect_uri={redirect-uri}
  &state={state-param}
```

See here: https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow/#checklogin.

To do that, we need to set in FB's settings. See the screenshot in answer https://stackoverflow.com/a/5270454, plus add Valid OAuth Redirect URLs.

**Comment by nicolay-zlobin** [comment]
Maybe it's not the case with vue-facebook-login-component. Just shared a possible solution.

**Comment by desert** [comment]
So it seems it **is** possible.

**Comment by adi518** [comment]
Well not exactly, because it's just another way to redirect to Facebook. The popup does the same thing, but keeps the user in the same window for an optimal user experience.
