### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by johanvanwambeke** [adi518/vue-facebook-login-component#5]
I installed the package as instructed, it showed up once and now i get.
Window is not defined.

I'm using vuetify and Nuxt

**Comment by adi518** [comment]
Hmm, haven't tested it with Nuxt, so that's probably why it doesn't work. I need to find out how Facebook SDK would work in that context.

**Comment by muscle-rhnkyr** [comment]
@johanvanwambeke Did you try to use https://nuxtjs.org/api/components-no-ssr/ ?

**Comment by adi518** [comment]
Sounds like there's a workaround. If demand for SSR increases, we'll reopen this issue. 👍

**Comment by platform-kit** [comment]
This issue is not solved for anyone using this plugin in a SSG other than Nuxt. Can you please make the necessary change? 

I believe it would be fixed simply by wrapping the entire function in 

```
if(typeof document != 'undefined'){
     //existing code goes here
}

```

the only reason the build fails is because of the references to the `window` and `document` objects which don't exist in the SSR context.

**Comment by adi-works** [comment]
Nuxt.js has a client-only hook, so I guess similar frameworks have something similar to that. Otherwise, can you start a PR?

**Comment by platform-kit** [comment]
Don't have the time (I work full-time as film editor), but it should be as simple as wrapping the entire exported method in that `if` statement.

**Comment by adi-works** [comment]
What did you try to build it for?
