### ISSUE TITLE
Permissions dialog not displaying

### ISSUE THREAD

**Issue by theoblkr** [adi518/vue-facebook-login-component#56]
The permissions dialog is not showing but I can be logged.  Actually, if I am connected on Facebook, the dialog is closing very quickly.

**Comment by adi518** [comment]
Sounds like you implemented it or setup your app incorrectly. I don't think it's an issue with the component. The dialog closes quickly because you are already logged in. The component has pass-throughs for Facebook SDK and Facebook Login options, so please look into that. I also suggest to search Stackoverflow, which is likely to yield relevant answers to your issue.
